# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://swqmaven.github.io/
date_format: "ordinal"
title: swqmaven
subtitle: "简单主义者，Java Full Stack ing。"
description: "swq的个人博客"
keywords: swq, maven, swqmaven
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: swqmaven
organization: Pioneerdata, Inc.
organization_url: https://www.anynode.com
location: Chongqing, China
email: wenqiang.shi@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: swqmaven/swqmaven.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: swqmaven
douban_username: swqmaven
facebook_username: swqmaven
weibo_username: swqmaven
zhihu_username: swqmaven
twitter_username: swqmaven

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: blueCloud
disqus_username: swqmaven
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Python, Micro service, Architecture]
skill_mobile_app_keywords: [Android, AIR]
skill_linux_keywords: [shell, HA, middleware]
